### PR TITLE
Trying to externalize strings

### PR DESCRIPTION
**Pull request by piedpiper358**
I can't fully understand how string localization works. Could you help me figure this out with a specific example. What am I missing here? LocalizationFacadeService should be passed in component? Where should it be done?

### CODE REVIEW

**Comment by sebastientromp** [comment]
If you simply use the directive (the `[helpTooltip]="'app.collection.sets.total-non-golden-cards' | owTranslate" part) you don't even need to import the service. It is only used if you want to call the API itself (e.g. translate strings inside the javascript code).

So from what I see here, this is looking good and should work.

One caveat though: the translations files are cached for a long time. To force a fetch of the new version, you need to update the version query string in `shared.module.ts`:

```
export function HttpLoaderFactory(http: HttpClient) {
	return new TranslateHttpLoader(http, 'https://static.firestoneapp.com/data/i18n/', '.json?v=116');
}
```
(just increment the 116 to some bigger number, or anything that you'd like)

**Comment by piedpiper358** [comment]
Thank you, everything worked out, but not for this case. What can I do here?

**Comment by piedpiper358** [comment]
After the last release, I can no longer build the project from source due to the error:
>"ERROR in src/js/services/decktracker/card-highlight/selectors.ts:136:42 - error TS2339: Property 'WHELP' does not exist on type 'typeof GameTag'.
136 export const whelp = hasMechanic(GameTag.WHELP);

Is the reference data also cached on the server? How can I force it to update?

**Comment by sebastientromp** [comment]
You just need to run `npm install` to update the dependencies

**Comment by piedpiper358** [comment]
Thanks))

**Comment by sebastientromp** [comment]
Can I close that one?

**Pull request closed without merging**
