### PR TITLE
Improve appearance of related cards tooltip

### PR DESCRIPTION
**Pull request by piedpiper358**
**Before:**

**After:**

### CODE REVIEW

**Comment by sebastientromp** [comment]
Would you mind also showing how this looks like in the deck tracker?

I feel like the related cards could become a bit blurred with the background if there is too much information (which is why I added this more opaque background in the first place)

**Comment by sebastientromp** [comment]
Thanks! It's still pretty legible, but to be honest I'm not sure I think this is an improvement over the current version. Probably just a matter of taste :)

For now I will close this PR, and we might come back to it in the future if I see people have issues with the current layout.

Thanks anyway for the suggestion :)

**Comment by piedpiper358** [comment]
**The killing feature of my proposal is that we get rid of those awful dark empty spaces. Isn't it worth it?**

**Comment by sebastientromp** [comment]
This is actually how it looked like at first. But I found that it could get a bit unclear when shown on screen with too much other pieces of info, which is why I opted for the current design.

**Comment by piedpiper358** [comment]
My last attempt at pushing this change: we remove empty dark space and leave the opacity at 1.

**Comment by sebastientromp** [comment]
Ok that one looks better, I'll reopen the PR

**Comment by sebastientromp** [comment]
I can't reopen the PR. Could you either try these steps https://gist.github.com/robertpainsi/2c42c15f1ce6dab03a0675348edd4e2c or reopen a new PR (with a comment linking it to this one)?

**Comment by piedpiper358** [comment]
You should now be able to reopen the PR.

**Pull request closed without merging**
