### PR TITLE
Improve graph-with-comparison tooltip layout

### PR DESCRIPTION
**Pull request by piedpiper358**
**Before:**

**After:**

### CODE REVIEW

**Comment by sebastientromp** [comment]
I don't see any externalized strings being used in this PR, is this intended?

**Comment by piedpiper358** [comment]
Yes, definitely)

**Comment by sebastientromp** [comment]
Got it :) The new strings should now be uploaded, so you should be able to test them

**Comment by piedpiper358** [comment]
#171 
I done it!

**Comment by sebastientromp** [comment]
Looks good, I'll merge that once tonight's patch aftermath is over :)

**Pull request merged**
