### PR TITLE
Add speed display for abilities with 0 speed

### PR DESCRIPTION
**Pull request by piedpiper358**

### CODE REVIEW

**Comment by piedpiper358** [comment]
**Before:**



**After:**

**Comment by sebastientromp** [comment]
Thanks. I would like to do some tests myself, as I think that 0-speed abilities not having the speed value shown indicates an underlying issue (the ability speed in the model should be 0 in that case, and not null).

**Comment by piedpiper358** [comment]
Yeah, and I fixed it. Now if the speed is not defined, then it is assigned the value 0. And in that case, we don't display speed only for equipment or passive treasures (with zero speed)

**Comment by sebastientromp** [comment]
Sorry, I think I used some notions that I never explained.
The "model" is what the game state looks like. It's basically what is computed in the `services` packages, and is sent to the "view", which is more or less what you have in the `components` folder.
I think it's important to fix the state itself, so that all other views / processes that depend on it will also use an accurate value. If you only fix it in the view (the components), then the value will still be incorrect (null, instead of 0) for all the other bits of the code that use it.

I'm not sure if what I'm saying makes sense, let me know :)

**Comment by piedpiper358** [comment]
I have a specialized education and am familiar with the MVC model, so it all makes sense for me. I just did't think that some other views also use the speed value of mercs abilities. If you tell me which way to look, I'll try to fix it.

**Comment by sebastientromp** [comment]
I'm not even sure other components use the speed value. It's just that fixing the symptom instead of the root cause in this case might make future me scratch my head when I implement more features that use this specific field.
Working on the services is probably more complex, and I can have a look myself. 

Do you have a recommended scenario to get a 0-speed ability?

**Comment by piedpiper358** [comment]
The initial value of the speed of the merc ability must be zero. So it should be Leeroy Jenkins or Queen Azshara. (If you don't have them, then I can share my team with you in a friendly match)

When you will fix this, please take a look at the following issues:
• Mercenaries who are affected by the slow effect gets an empty ability. (The easiest way to reproduce the error is in a friendly match or go to Heroic 1-1 and meet Grommash + Kern comp there)

• The first trigger of treasures such as Volley of Light or Fire Volley (which passively cast abilities on a condition) this applied ability itself appears in the list of abilities as if the mercenary actually has it. (The easiest way to reproduce it is to take Tyrael into team - he often gets Volley of Light)

Both of this bugs can be seen on this screenshot:

**Comment by sebastientromp** [comment]
I unfortunately don't have either of them. So I'm down for team sharing when I'm back (around end of August) :)

**Comment by sebastientromp** [comment]
> The first trigger of treasures such as Volley of Light or Fire Volley (which passively cast abilities on a condition) this applied ability itself appears in the list of abilities as if the mercenary actually has it. (The easiest way to reproduce it is to take Tyrael into team - he often gets Volley of Light)

Will be fixed in the next release

**Comment by sebastientromp** [comment]
> Mercenaries who are affected by the slow effect gets an empty ability. (The easiest way to reproduce the error is in a friendly match or go to Heroic 1-1 and meet Grommash + Kern comp there)

So what is happening here is that the debuff is applied to the passive treasure. This will also be fixed in the next release

**Comment by piedpiper358** [comment]
Glad it will be fixed soon)
I would also like to note that treasures that resurrect mercenaries (such as Resurrection and Absolution) do not have their effect on the team widget (merc still greyed)

Here is the resurrected Xyrella:

**Comment by sebastientromp** [comment]
Got it, adding it to my list. I'll have to add a new event for resurrected mercs

**Comment by piedpiper358** [comment]
And also, if you change the current team during completing of bounty, then these changes will be displayed on the 'Team widget: Map'. However, I'm not sure that this can be avoided.

**Comment by sebastientromp** [comment]
I inadvertently got a 0 speed ability, and it was displayed properly

image

So maybe the display issue only occurs when the speed is naturally 0 (without buffs)

**Comment by sebastientromp** [comment]
I will do a tentative fix for the 0 speed ability. From what I've seen it looks like the data extracted from the game file has no "cost" (aka speed in mercs) for these abilities, so I'll default it to 0 when creating the ability in-app.

**Comment by piedpiper358** [comment]
I will make the appropriate changes as soon as I see your changes and can test everything. In any case, it is necessary to change the speed display condition, because recently I encountered that during the battle passive treasure acquired speed value.

**Comment by piedpiper358** [comment]
I finally tested it all out. Now it should work great.

**Comment by sebastientromp** [comment]
Here I think I would go the same route as the previous discussion: I think having speeds for passive abilities doesn't make sense, so I would prevent that in the model itself.

Also, I think that non-passive treasures can have speeds, no?

It looks like the card reference for these passive skills have the HIDE_STATS mechanic, so maybe we can use that tag?

**Comment by piedpiper358** [comment]
> It looks like the card reference for these passive skills have the HIDE_STATS mechanic, so maybe we can use that tag?
It is likely that this will be the best solution, because perhaps later there will be active treasures with zero speed (as I understand it, at the moment there are none)

> Also, I think that non-passive treasures can have speeds, no?
Of course, active treasures should have a speed value.

**Comment by sebastientromp** [comment]
Got it. I'll look into it then.

**Comment by piedpiper358** [comment]
**Fixed debuff not being colored for zero speed abilities**

**Before:**



**After:**

**Pull request merged**
