### PR TITLE
Change Witchwood logo

### PR DESCRIPTION
**Pull request by piedpiper358**
**Before:**

**After:**

### CODE REVIEW

**Comment by sebastientromp** [comment]
image

On the official website the logo looks like the original one.  
Why did you propose the change?

**Comment by piedpiper358** [comment]
If you look closely, you will see that on official website third version of the logo. It's probably even better than my version.

> Why did you propose the change?

Because it's embarrassing that the name of the set is smaller than Hearthstone title.

**Comment by sebastientromp** [comment]
Thanks, this looks indeed better than the other one. I'll merge it once I'm done with the current release

**Pull request merged**
