### PR TITLE
Full-card.component improvements

### PR DESCRIPTION
**Pull request by piedpiper358**
• Add new types of card sounds: "Wow", "Picked", "Happy Holidays"
• Add recognition of alternate spellings of some sound filenames
• Remove capitalization of sound filenames because it looks pretty bad in some Non-English languages
• Remove "[x]" from cards flavor text found in Kazakus (BoM Kurtrus' story) and Lady Anacondra (BoM Guff's story)
• Fix multi-class cards bug

• Add check for undefined card class
• Add card rarity display

### CODE REVIEW

**Comment by sebastientromp** [comment]
Yeah, I'll merge it once I am satisfied with all the changes :)
And it's not an issue to add new entries in firestone-translations first - they will simply not be used until the code is merged in the main app.

**Comment by piedpiper358** [comment]
There are so many issues in Firestone for now. And I would love to fix them all, but if the changes take that long to apply, it will take years...

**Comment by sebastientromp** [comment]
I understand how you feel. There are a few things to keep in mind though:  

- Approving a PR is usually more work than doing it myself from scratch. Which is why I ask for PRs that are as small as possible, so I can merge things as I validate them (this one is a good example of how to do it right)
- You haven't replied to my comment on the removal of the "capitalize" rule in the scss file, so I can't decide whether to accept this change or not
- I'm currently on vacation :)

**Comment by piedpiper358** [comment]
Speaking of of minimizing pull-requests, I think I learned. And the "Dust Recap" was minimally small, but it still wasn't accepted.
I think it's kind of general rule of programming for localized apps, that source string shouldn't be changed somewhere in code (capitalized or '+' added). This complicates the work of localizers. It should be done in source string instead. 
For example, in Russian, a capitalized sentence looks unacceptable (e.g. "Я Уже Атаковал(А)")

Have a good rest :)

**Pull request merged**
