### PR TITLE
Update image for Throne of the tides mini set

### PR DESCRIPTION
**Pull request by piedpiper358**

### CODE REVIEW

**Comment by sebastientromp** [comment]
Thanks! Could you make sure that the image uses the same amount of transparent space around it as the other mini-set images? Basically, the mini-set and the main set images should be identical, except for the "mini-set" part.

Let me know if you need help doing it, and I'll resize the image myself

**Comment by piedpiper358** [comment]
Yes, it is now a little larger than the others, but I thought it might make sense to increase them all? Logo takes only about 60% of block width and many inscriptions are not readable due to small size.

**Comment by sebastientromp** [comment]
For now I'd rather have this image in line with the others, and then we can look into making everything bigger

**Comment by piedpiper358** [comment]
Fixed

**Comment by sebastientromp** [comment]
Thanks!

**Comment by sebastientromp** [comment]
One last request: could you resize it to make it smaller (eg 500px width) so that it doesn't make the app too much bigger?

**Comment by piedpiper358** [comment]
Done

**Pull request merged**
