### PR TITLE
Improve layout of decktracker-deck-details

### PR DESCRIPTION
**Pull request by piedpiper358**
**Before:**

**After:**

**Before:**

**After:**

**Before:**

**After:**

**Before:**

**After:**

### CODE REVIEW

**Comment by sebastientromp** [comment]
I prefer to keep things aligned to the sides, rather than have them float to the center (at least in this case). 

As a general rule, I'm not sure it's such a good idea to open PRs just to make things look better (unless it's a real overhaul and brings something new). Aesthetics are pretty subjective, and the added value of the changes is IMO usually not worth the time spent coding / reviewing everything.

**Comment by piedpiper358** [comment]
> I prefer to keep things aligned to the sides, rather than have them float to the center (at least in this case).

I can do it easily.


It's not just about making things look better, it's more than that. It's about:
* Spreading space more evenly: shrinking the enormous chart and first column of the table, and thereby increasing space for deck versions.
* Making the style of the inscription Deck versions the same as all the others.
* Improving the appearance of the localized Reset stats button

**Comment by piedpiper358** [comment]
> I prefer to keep things aligned to the sides, rather than have them float to the center (at least in this case).

So do you like it better?

**Comment by sebastientromp** [comment]
Yes this is looking better to me. Would you mind also adding some screenshots of what it looks like at smaller screen sizes?

**Comment by piedpiper358** [comment]
> I prefer to keep things aligned to the sides, rather than have them float to the center (at least in this case).

Could you please re-open the PR. I will make the appropriate changes.

**Comment by piedpiper358** [comment]
> Would you mind also adding some screenshots of what it looks like at smaller screen sizes?

Minimum window size:

**Comment by sebastientromp** [comment]
Sorry, I forgot to reopen the PR

Also, instead of using labels it's probably better to assign the PR to the right person (so to me if you did an update / new PR, and to you if I have comments for you)

**Comment by piedpiper358** [comment]
> Also, instead of using labels it's probably better to assign the PR to the right person

But as far as I understand, I can't assign you to PR.

Changes are already in the branch.

**Comment by sebastientromp** [comment]
Ah I didn't know that it worked like that. 
I guess that as long as you can remove your own assignment that's good enough.

**Pull request merged**
