### PR TITLE
LOC: externalize strings

### PR DESCRIPTION
**Pull request by piedpiper358**

### CODE REVIEW

**Comment by sebastientromp** [comment]
I think we should first find a way for you to be able to test the changes that you propose via the PR. As they are, reviewing them takes a lot of time for me to catch things that won't pass the compiler. If you are able to do all of this locally and then test the changes for yourself, you'll be able to catch these errors yourself before submitting the PRs.

**Comment by sebastientromp** [comment]
Compiling the app locally is something you can already do yourself (loading a locally compiled app is probably not possible as of today, I'm checking this with Overwolf).

You can check all the instructions in the README.md file

**Comment by piedpiper358** [comment]
It seems to me that the instructions for contributing are not written in sufficient detail. What tools do I need to install besides Node.js and Python? Do I need to clone all repositories or just Zero-to-Heroes/firestone?

**Comment by piedpiper358** [comment]
Ok, but, npm install fails with the error "Can't find Python executable "python", you can set the PYTHON env variable."
[2022-08-08T20_26_22_257Z-debug-0.log](https://github.com/Zero-to-Heroes/firestone/files/9284873/2022-08-08T20_26_22_257Z-debug-0.log)


After I installed Python, it now fails with "Command failed: C:\Users\F1RRA\AppData\Local\Programs\Python\Python310\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];".
[2022-08-08T20_56_53_765Z-debug-0.log](https://github.com/Zero-to-Heroes/firestone/files/9285033/2022-08-08T20_56_53_765Z-debug-0.log)

**Comment by sebastientromp** [comment]
Thanks for the logs, I don't remember having had to install anything specific for this, but it's been a while ago.

Unfortunately I don't really have time right now to look into it, but should have more time for that next week.

**Comment by piedpiper358** [comment]
I dealt with the errors that occurred and now the project seems to be building normally.
I loaded my built to Overwolf's Package Manager, but when I click Launch button, nothing happens. I think this is because I need to be whitelisted in OW in order to add unpacked extensions. (https://overwolf.github.io/start/basic-app/sample-app)
If this is indeed the case, then what should I include in my proposal to OW?

**Comment by sebastientromp** [comment]
Awesome! Would you mind documenting the steps that you took to fix everything? I will include them in the README.

And you can just give me your Overwolf username, I'll contact OW directly

**Comment by piedpiper358** [comment]
Things that I needed to install to fix the errors:
• Node.js version 14 (the latest version (16.06) is not suitable)
• Visual Studio Build Tools 2017
• Windows SDK

My username is @bos.sapozhnikov
I would be very grateful for your help whitelisting me)

**Comment by sebastientromp** [comment]
Hey, you should be whitelisted now! You might have to log out then back in.
Let me know if this works :)

**Comment by piedpiper358** [comment]
Yes, finally everything works great! Thanks a lot :D

**Comment by sebastientromp** [comment]
Were you able to test this? I saw a commit pass about things not working, but it doesn't exist anymore, so I'm not totally sure if this is working properly on your side yet.

**Pull request closed without merging**
