### PR TITLE
Fix minions tooltip in simulator

### PR DESCRIPTION
**Pull request by piedpiper358**
**Before:**

**After:**

### CODE REVIEW

**Comment by sebastientromp** [comment]
Thanks for fixing all these little bugs!

**Comment by piedpiper358** [comment]
These bugs pissed me off for so long that I'm happy to finally fix them)

**Comment by sebastientromp** [comment]
Totally understand the feeling :)

**Comment by piedpiper358** [comment]
Sebastien, but there are still problems here: many of the BG cards display a mana crystal. This problem is right in the files on the server. This problem is not as bad in English (1-2 cards) as it is in Russian or Italian (about half of the cards). Is it possible to regenerate them without a mana crystal?




Here are some of them:
https://static.firestoneapp.com/cards/bgs/enUS/512/TB_BaconShop_HERO_21_Buddy.png
https://static.firestoneapp.com/cards/bgs/enUS/512/TB_BaconShop_HERO_93_Buddy.png
https://static.firestoneapp.com/cards/bgs/ruRU/512/TB_BaconShop_HP_105t.png

**Comment by sebastientromp** [comment]
Thanks, looking at the card image you can see there is the BG stars, but they are hidden behind a mana crystal that should have disappeared. I will indeed need to regenerate all of these. Thanks!

**Comment by piedpiper358** [comment]
I will be glad if it soon ceases to be an eyesore to me)

**Comment by sebastientromp** [comment]
I have regenerated everything, it should be better now

**Comment by piedpiper358** [comment]
Yes, it got better, but mana crystals are still on about 25 cards in Russian. I would give a list of them, but it will be easier to take a look for yourself.

**Comment by sebastientromp** [comment]
My bad, I forgot that some old minions were not part of the Battlegrounds set. I will regenerate them when I come back end of the month

**Comment by piedpiper358** [comment]
**Also required:**

• Generate images for new card backs



• Regenerate some portraits from the Book of Mercenaries



• Generate card image for N'Zoth 



• Update role info for Uther



• Add role info for latest mercenaries

**Pull request merged**
