### PR TITLE
Normalize merc task texts for Russian

### PR DESCRIPTION
**Pull request by piedpiper358**
**Before:**

**After:**

**Before:**

**After:**

### CODE REVIEW

**Comment by sebastientromp** [comment]
Thanks for the suggestion! I will however probably need to address this directly at the stage where I'm building the reference files

**Comment by sebastientromp** [comment]
Sorry, I understand you want to have this integrated quickly, but this really should be integrated in the data parser and not the app itself.
I'll see if I can put it on my todo list for next week

**Comment by piedpiper358** [comment]
@sebastientromp, Thank you. Should I implement the same for quest and achievement texts for now? Could you add it all together?

**Comment by sebastientromp** [comment]
I will look into everything at the same time. They are not in the same game files, but I hope the logic is the same for all texts

**Pull request closed without merging**
