### PR TITLE
Improve minion selection window layout

### PR DESCRIPTION
**Pull request by piedpiper358**
**Before:**

**After:**

### CODE REVIEW

**Comment by sebastientromp** [comment]
This looks good, but I want to test the changes locally first, as I don't have the same broken display as you do in the first place :)

**Comment by piedpiper358** [comment]
Yes, in English I don’t have such a problem either, so it’s a matter of localization.

**Comment by sebastientromp** [comment]
Got it, I'll check that

**Comment by piedpiper358** [comment]
By the way, here we need to change font color of "Search minion" label

**Pull request merged**
