### PR TITLE
Change achievements categories separator

### PR DESCRIPTION
**Pull request by piedpiper358**
**Before:**

**After:**

### CODE REVIEW

**Comment by sebastientromp** [comment]
I'm not a big fan of how this look to be honest. Maybe with a lighter ">"?

**Comment by piedpiper358** [comment]
Which one do yoг like more?

**Comment by piedpiper358** [comment]
I also want to change icons for new expansions, but I couldn't find anywhere in the code where to change filenames.

**Comment by sebastientromp** [comment]
> Which one do yoг like more?
> 
> 

Maybe the ones between opt5 and 6, or 6 and 7

**Comment by sebastientromp** [comment]
> I also want to change icons for new expansions, but I couldn't find anywhere in the code where to change filenames.
> 
> 

Do you have an svg of the recent expansions?

**Comment by piedpiper358** [comment]
Yeah, I have.  Thanks to https://hearthstone.fandom.com/

**Comment by sebastientromp** [comment]
Perfect. Then the svg files are all located under `assets/svg/achievements/categories/` and use the set id as the file key.
I'll merge this PR and the svg files update can be done in another one.

**Comment by piedpiper358** [comment]
I uploaded files there with the appropriate names, but it didn't seem to work. Should I do something else?

**Comment by piedpiper358** [comment]
Do you like it better?

**Comment by sebastientromp** [comment]
> I uploaded files there with the appropriate names, but it had no effect. Should I do something else?

Have you tried recompiling the app (npm run dev)?

**Comment by sebastientromp** [comment]
> Do you like it better?
> 
> 

I'm not a big fan of the separator being used. Could you try using the same shape as the one already used in the app? And make sure it's a pretty light weight and/or with sufficient left and right spaces?

**Comment by piedpiper358** [comment]
> Maybe the ones between opt5 and 6, or 6 and 7

Do you like?




> Have you tried recompiling the app (npm run dev)?

Yes, I even did `npm install`


> Could you try using the same shape as the one already used in the app?

But we don't seem to be able to use the svg file here

**Pull request merged**
