### PR TITLE
Improve simulator tooltip

### PR DESCRIPTION
**Pull request by piedpiper358**
**Before:**

**After:**

### CODE REVIEW

**Comment by sebastientromp** [comment]
Looking at the code, I'm not sure that it actually fixes the issue.
I've seen this weird tooltip layout appear from time to time. It's usually fixed after restarting the app, sometimes even by navigating away and then back to the page. 
It looks as if parts of the CSS aren't loaded in these cases, but I haven't yet found a way to reproduce it consistently, which makes it harder to fix.

**Comment by piedpiper358** [comment]
> Looking at the code, I'm not sure that it actually fixes the issue.

Agree.


I did a little research and I suggest you repeat the following steps after me to clearly see everything for yourself:
* Go into Simulator and make sure that tooltip is displayed correctly
* Go to Replays view
* Go back to the Simulator and make sure the tooltip is now broken

You can restart Firestone and repeat these steps a few times to make sure this happens every time.

(Actually, tooltip breaks on many views, but we took the Replays view as an example because there is only one tab)

Now if we change the tooltip body class from `content` to, for example, `content2` (in both `battlegrounds-simulator.component.ts` and `help-tooltip.component.scss`) and repeat the steps above, we will see that the tooltip is no longer breaks, that is, all this is connected with the `content` class. (Reversely replace class `content2` with `content`)

Through trial and error, I found out that the reason specifically in the case of  Replays view was one rule in `replays.component.css`

`.content{`
`::ng-deep & > * { display: flex; min-height: 0; opacity: 1 }`
`}`

If you remove it, repeat the steps above, then you will make sure that tooltip doesn't breaks anymore.

In my opinion, what is happening here is not the unloading of css rules, as you say, but leakage of css rules from other components when switching to them. The same things was happening [here](https://github.com/Zero-to-Heroes/firestone/pull/138), but then you paid insufficient attention to my message.

According to [Angular documentation](https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep/#:~:text=the%20style%20can%20bleed%20into%20other%20components), using `::ng-deep` pseudo-class without a preceding `:host` causes rule to bleed into other components. It still seems to me that it is necessary to reconsider the use of `::ng-deep` pseudo-class in each case to finally eliminate leakage of rules between components and appearance of such subtle bugs.


Now if we set the `:host` pseudo-class in front of this rule 

`.content{`
`:host ::ng-deep & > * { display: flex; min-height: 0; opacity: 1 }`
`}`
and repeat the steps above, the tooltip again no longer breaks. I hope all this proves convincingly enough that css rule leakage occurs here.

(P.S. If I didn't explain something clearly enough, feel free to clarify with me. I wish we could finally sort out this annoying bug!)

**Comment by sebastientromp** [comment]
Issue reproduced, thanks for the detailed explanations!

And well done finding the root cause. I will see if adding :host before ::ng-deep in all SCSS files solve the issue and/or introduces new problems.

**Comment by sebastientromp** [comment]
Ok I didn't think this through :)

:host is a selector, so if you apply it nested inside a rule, it won't match anything. It should be set at the start of the rule, to match the current component, and then apply the ::ng-deep rule as a child.
So it will take a bit longer than anticipated.

**Comment by sebastientromp** [comment]
I have guarded a few ::ng-deep calls (including the ones you mention in the comment above) with :host, and it seems to fix the issue without introducing side-effects.
I will close this PR.

Thanks again for all the investigations!

**Comment by piedpiper358** [comment]
@sebastientromp, 
You are welcome! I am very glad that we were finally able to deal with this annoying bug!
I really like what we are doing today in terms of development of Firestone. It seems to me that recently Firestone is rapidly changing for the better. But I would be pleased if my contribution to the project was somehow monetized. Don't you think that my contribution deserves some kind of financial incentive?
It’s not very convenient for me to ask you about this, so if you say no, then I won’t be offended)

**Comment by sebastientromp** [comment]
Sorry for the late reply. For now, I don't plan to support paid contribution to Firestone, though it might change in the future.
The reasons are:
- it adds quite a lot of administrative hassle. I'm in France, and work as a registered (one-person) corporation, and paying someone to work for you is very strictly regulated. At the very minimum, you would need to have yourself a legal entity that could send me invoices.
- if/when I finally decide to get someone (paid) to work with me, it will very likely be in an area I am not already proficient in, to compliment my own skillset (eg data science / machine learning, marketing, UX/UI).

I'm sorry I can't compensate you financially, and totally understand if you wish to step back from helping with the project.

**Pull request closed without merging**
