### PR TITLE
Mercenaries-personal-hero-stats improvements

### PR DESCRIPTION
**Pull request by piedpiper358**
• In some non-English languages, coin сolumns headers require a little bit more space (e.g. in Russian and Chinese). While the name column takes up too much space.

• In some non-English languages, the "Max level" label may span two lines and then be left-aligned (see screenshot above). It should be center aligned to look nice.

• Abilities/equipment tooltips are too far away from the elements. I don't see the need for such distancing.

### CODE REVIEW

**Comment by sebastientromp** [comment]
I'm wondering, are you able to test the changes that you propose in the PRs?

**Comment by piedpiper358** [comment]
Actually, no. My changes were so small and simple that it didn't seem necessary for me. I will try to figure out how I can test it. 
Are there any big problems there?

**Comment by sebastientromp** [comment]
When I tested the changes it looked like that the columns were not properly aligned anymore. 
Also the width change didn't seem to do anything, so I was wondering what purpose it served

**Comment by piedpiper358** [comment]
Now it's much better.

**Comment by piedpiper358** [comment]
Any other problems with these changes?

**Comment by sebastientromp** [comment]
No it's looking good, let's merge it. Thanks again :=)

**Comment by piedpiper358** [comment]
Thank you)

**Pull request merged**
