### PR TITLE
Fix appearance of empty abilities in mercs team widget

### PR DESCRIPTION
**Pull request by piedpiper358**
**Before:**

**After:**

### CODE REVIEW

**Comment by sebastientromp** [comment]
Here I think it's probably best to not add the ability to the model itself if the data is incomplete. I don't have a clear reproduction scenario yet though

**Comment by piedpiper358** [comment]
Casting Malfurion's Cenarion Surge ability also causes an empty ability to appear.

**Comment by sebastientromp** [comment]
@piedpiper358 This should be fixed on the latest beta build now. Can you confirm?

**Comment by piedpiper358** [comment]
Yes, I don't run into this error anymore.

**Pull request closed without merging**
